In [1]:
# sources:
# http://ais.informatik.uni-freiburg.de/teaching/ws10/robotics2/pdfs/rob2-10-camera-calibration.pdf
# https://ksimek.github.io/perspective_camera_toy.html
# https://towardsdatascience.com/camera-intrinsic-matrix-with-example-in-python-d79bf2478c12
# http://www.info.hiroshima-cu.ac.jp/~miyazaki/knowledge/teche0092.html
#https://ksimek.github.io/2012/08/14/decompose/

In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
!pip install -U kaleido

Defaulting to user installation because normal site-packages is not writeable


In [3]:
!pip install plotly

Defaulting to user installation because normal site-packages is not writeable


In [675]:
# # Create a 3D plane mesh using the meshgrid function
# x = np.linspace(-10, 10, 50)
# y = np.linspace(-10, 10, 50)
# z = np.linspace(-10, 10, 50)
# X, Y= np.meshgrid(x, y)

# print(X.shape)
# print(Y.shape)
# print(Z.shape)

# mesh_3d = go.Mesh3d(x=x,y=y,z=np.sin(x), color='green', opacity=0.20)
# #mesh_3d = go.Mesh3d(x=x,y=y,z=z, color='green', opacity=0.20)
# fig = go.Figure(data = [mesh_3d])
# fig.show()
# np.meshgrid((x,y,z))

In [64]:
t = np.linspace(0, 10, 100)
x, y, z = t, np.cos(t)*10, np.sin(t)*10
#x, y,z = np.random.randint(0,15,100), np.random.randint(0,15,100) ,np.random.randint(0,5,100)
x, y= np.random.randint(0,15,100), np.random.randint(0,15,100)
z = 0.5*x+2*y
#print(x)
cam1 = np.array([5,5,30])
cam1_x = cam1[0]
cam1_y = cam1[1]
cam1_z = cam1[2]

cam2 = np.array([8,6,25])
cam2_x = cam2[0]
cam2_y = cam2[1]
cam2_z = cam2[2]

x = np.append(x,cam1_x)
y = np.append(y,cam1_y)
z = np.append(z,cam1_z)

x = np.append(x,cam2_x)
y = np.append(y,cam2_y)
z = np.append(z,cam2_z)

#cam_x = np.linspace(20,25,10)
#cam_y = np.full(10,20)
#cam_z = np.ones(10)
#mesh_3d
fig = go.Figure(data=[go.Scatter3d(
    x=x,
    y=y,
    z=z
    mode='markers',
    marker=dict(
        size=5,
        color=x,                # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
)])



fig.update_layout(margin=dict(l=0, r=0, b=0, t=0))
fig.show()




#fig = go.Figure(data=[go.Mesh3d(x=x, y=y, z=z, colorscale='Viridis', opacity=0.50)])
#fig.show()

# plt.scatter(x,z)
# plt.xlabel("x")
# plt.ylabel("y")
# plt.title('X - Y view')

# plt.scatter(x,z)
# plt.xlabel("x")
# plt.ylabel("z")


SyntaxError: invalid syntax. Perhaps you forgot a comma? (189266415.py, line 32)

In [10]:
name = 'eye = (x:0., y:3, z:0.)'
camera = dict(
    eye=dict(x=0., y=3, z=0)
)


fig.update_layout(scene_camera=camera, title=name)
fig.show()


In [65]:
name = 'eye = (x:0., y:0, z:2)'
camera = dict(
    eye=dict(x=0., y=0, z=2)
)


fig.update_layout(scene_camera=camera, title=name)
fig.show()


In [66]:
name = 'eye = (x:2., y:0, z:0)'
camera = dict(
    eye=dict(x=3, y=0, z=0)
)


fig.update_layout(scene_camera=camera, title=name)
fig.show()

In [67]:
#define camera calibration matrix

#camera_1

#K-matrix
c1_f = .02 #20mm lens
c1_u = 0.01
c1_v = 0.02
c1_sk = 0.005

c1_k = np.array([
    [c1_f, c1_sk, c1_u],
    [0, c1_f, c1_v],
    [0,0,1]
])

#camera intrinsic
ang1 = np.radians(60)
#defining rotation about z axis:
c1_r11 = np.cos(ang1)
c1_r12 = -np.sin(ang1)
c1_r13 = 0
c1_r21 = np.sin(ang1)
c1_r22 = np.cos(ang1)
c1_r23 = 0
c1_r31 = 0
c1_r32 = 0
c1_r33 = 1

c1_tx= cam1_x
c1_ty= cam1_y
c1_tz= cam1_z

#completing rotation matrix
# c1_r = np.array([
#     [c1_r11, c1_r12, c1_r13, 0],
#     [c1_r21, c1_r22, c1_r23, 0],
#     [c1_r31, c1_r32, c1_r33, 0],
#     [0,0,0,1]
# ])

c1_r = np.array([
    [c1_r11, c1_r12, c1_r13],
    [c1_r21, c1_r22, c1_r23],
    [c1_r31, c1_r32, c1_r33]
])

#completing translation matrix
# c1_t = np.array([
#     [1,0,0,c1_tx],
#     [0,1,0,c1_ty],
#     [0,0,1,c1_tz],
#     [0,0,0,1]]
# )

c1_t = np.array([
    [1,0,c1_tx],
    [0,1,c1_ty],
    [0,0,c1_tz]]
)




c1_ex = np.matmul(c1_t, c1_r)
c1_p = np.matmul(c1_k, c1_ex)

print('Rotation Matrix for Camera 1:\n', c1_r)
print('\nTranslation Matrix for Camera 1:\n', c1_t)
print('\nExtrinsic Matrix for Camera 1:\n', c1_ex)
print('\nIntrinsic Matrix for Camera 1:\n', c1_k)
print('\nProjection Matrix for Camera 1:\n', c1_p)




#camera_2
c2_f = .02 #20mm lens
c2_u = 0.01
c2_v = 0.02
c2_sk = 0.005

c2_k = np.array([
    [c2_f, c2_sk, c2_u],
    [0, c2_f, c2_v],
    [0,0,1]
])


#defining rotation about z axis:

ang2 = np.radians(30) #angle of rotation
c2_r11 = np.cos(ang2)
c2_r12 = -np.sin(ang2)
c2_r13 = 0
c2_r21 = np.sin(ang2)
c2_r22 = np.cos(ang2)
c2_r23 = 0
c2_r31 = 0
c2_r32 = 0
c2_r33 = 1

#defining translation
c2_tx= cam2_x
c2_ty= cam2_y
c2_tz= cam2_z

#completing the rotation matrix
# c2_r = np.array([
#     [c2_r11, c2_r12, c2_r13, 0],
#     [c2_r21, c2_r22, c2_r23, 0],
#     [c2_r31, c2_r32, c2_r33, 0],
#     [0,0,0,1]
# ])


c2_r = np.array([
    [c2_r11, c2_r12, c2_r13],
    [c2_r21, c2_r22, c2_r23],
    [c2_r31, c2_r32, c2_r33]
])


#completing the translation matrix
# c2_t = np.array([
#     [1,0,0,c2_tx],
#     [0,1,0,c2_ty],
#     [0,0,1,c2_tz],
#     [0,0,0,1]]
# )

c2_t = np.array([
    [1,0,c2_tx],
    [0,1,c2_ty],
    [0,0,c2_tz]]
)

c2_ex = np.matmul(c2_t, c2_r)
c2_p = np.matmul(c2_k, c2_ex)
print('\n\n\nRotation Matrix for Camera 2 :\n',c2_r)
print('\n Translation Matrix for Camera 2 :\n', c2_t)
print('\nExtrinsic Matrix for Camera 2:\n', c2_ex)
print('\nIntrinsic Matrix for Camera 2:\n', c2_k)
print('\nProjection Matrix for Camera 2:\n', c2_p)

Rotation Matrix for Camera 1:
 [[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]

Translation Matrix for Camera 1:
 [[ 1  0  5]
 [ 0  1  5]
 [ 0  0 30]]

Extrinsic Matrix for Camera 1:
 [[ 0.5       -0.8660254  5.       ]
 [ 0.8660254  0.5        5.       ]
 [ 0.         0.        30.       ]]

Intrinsic Matrix for Camera 1:
 [[0.02  0.005 0.01 ]
 [0.    0.02  0.02 ]
 [0.    0.    1.   ]]

Projection Matrix for Camera 1:
 [[ 1.43301270e-02 -1.48205081e-02  4.25000000e-01]
 [ 1.73205081e-02  1.00000000e-02  7.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00  3.00000000e+01]]



Rotation Matrix for Camera 2 :
 [[ 0.8660254 -0.5        0.       ]
 [ 0.5        0.8660254  0.       ]
 [ 0.         0.         1.       ]]

 Translation Matrix for Camera 2 :
 [[ 1  0  8]
 [ 0  1  6]
 [ 0  0 25]]

Extrinsic Matrix for Camera 2:
 [[ 0.8660254 -0.5        8.       ]
 [ 0.5        0.8660254  6.       ]
 [ 0.         0.        25.       ]]



In [68]:
#ptss = np.vstack((x,y,z, np.ones(len(x))))[:,:100]
ptss = np.vstack((x,y,z))[:,:100]
print(ptss.shape)
print(x)
print(y)
print(z)

(3, 100)
[ 6 10  8  7  4 14  1  2  2 14 10  3 11 14 13 14  4  2 11  0 13  5 14 11
 10  1  5  3  8 14  6  3  1  4 11 13  5  7 12  4  9 12 11  5  2 14 12 11
  0  6 11  9  3 11  1  0  4  1  7  2  6  3  2 13 11 11  5  9 13  2  3  0
  9  0  3 10  4  1  7 11  1  0 14  2  1 10  4  0 14 13  5  2 13  0  6 14
  1  0 12  4  5  8]
[11 11  8  4  3 12 14  2  5  6  8  9  0 14  0  1  1  2 12  7  9 10 13 12
 11 12  3  4  7  8 11  3  8 10  5  4  4 13 10  4  9  7  9 13  7 10 14 14
  4  4 14 11  2  6  7 12 11 10  5  7  1 10  8  3  1 12  8 11  9  7  8 10
  7 13 10  8 13  1  7  9  7 14  0  8  0  8  2 10  5  4  4  8 10 10  7  0
 12 14  5 11  5  6]
[ 3  4  3  4  2  1  2  0  1  1  0  2  2  4  0  0  4  2  1  1  0  1  3  0
  2  3  3  2  3  2  4  1  1  0  4  1  0  2  4  2  0  3  3  1  0  0  2  1
  4  3  1  0  3  1  1  3  3  2  2  4  4  2  1  4  4  1  2  4  2  3  1  2
  1  1  2  4  1  2  2  0  0  0  3  1  0  1  2  3  4  0  4  4  1  0  4  4
  3  4  4  1 30 25]


In [69]:
pts_o = np.matmul(c1_p, ptss)
x_c1 = pts_o[0,:]
y_c1 = pts_o[1,:]
z_c1 = pts_o[2,:]

In [70]:
fig_c1 = go.Figure(data=[go.Scatter3d(
    x=x_c1,
    y=y_c1,
    z=z_c1,
    mode='markers',
    marker=dict(
        size=5,
        color=x,                # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
)])



fig_c1.update_layout(margin=dict(l=0, r=0, b=0, t=0))
fig_c1.show()

In [71]:
name = 'eye = (x:0., y:3, z:0.)'
camera = dict(
    eye=dict(x=0., y=3, z=0)
)


fig_c1.update_layout(scene_camera=camera, title=name)
fig_c1.show()

In [72]:
name = 'eye = (x:0., y:0, z:2)'
camera = dict(
    eye=dict(x=0., y=0, z=2)
)


fig_c1.update_layout(scene_camera=camera, title=name)
fig_c1.show()

In [73]:
name = 'eye = (x:2., y:0, z:0)'
camera = dict(
    eye=dict(x=3, y=0, z=0)
)


fig_c1.update_layout(scene_camera=camera, title=name)
fig_c1.show()

In [74]:
pts_o2 = np.matmul(c2_p, ptss)
x_c2 = pts_o2[0,:]
y_c2 = pts_o2[1,:]
z_c2 = pts_o2[2,:]

In [75]:
fig_c2 = go.Figure(data=[go.Scatter3d(
    x=x_c2,
    y=y_c2,
    z=z_c2,
    mode='markers',
    marker=dict(
        size=5,
        color=x,                # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
)])



fig_c2.update_layout(margin=dict(l=0, r=0, b=0, t=0))
fig_c2.show()

In [76]:
name = 'eye = (x:0., y:3, z:0.)'
camera = dict(
    eye=dict(x=0., y=3, z=0)
)


fig_c2.update_layout(scene_camera=camera, title=name)
fig_c2.show()

In [77]:
name = 'eye = (x:0., y:0, z:2)'
camera = dict(
    eye=dict(x=0., y=0, z=2)
)


fig_c2.update_layout(scene_camera=camera, title=name)
fig_c2.show()

In [78]:
name = 'eye = (x:2., y:0, z:0)'
camera = dict(
    eye=dict(x=3, y=0, z=0)
)


fig_c2.update_layout(scene_camera=camera, title=name)
fig_c2.show()

In [83]:
#Part iv - v

print(pts_o.shape)
print(pts_o2.shape)

(3, 100)

In [100]:
#calculating homography
h,_ = cv2.findHomography(pts_o.T,pts_o2.T)

In [101]:
#applying homography over the points
pts_o2_h = np.matmul(h, pts_o2)
print(pts_o2_h.shape)

(3, 100)


In [103]:
#calculating mean squared error
mse_axis = ((pts_o2_h - pts_o)**2).mean(axis=1)
print(mse_axis)

[1.80120476e-01 5.87861134e-02 1.53998535e+02]


In [107]:
mse = (np.sum(mse_axis)/3)**2
print(mse)

2643.2431660696716
